var JSON_TYPES = [
    { key: 'dialog_level_chapter', label: '对话-关卡(章节)', icon: '📖', desc: 'Chapter.json，顶层为天数键', category: '0.16.0改版' },
    { key: 'dialog_level_day', label: '对话-关卡(天数)', icon: '📅', desc: 'Day.json，含start/end场景', category: '0.16.0改版' },
    { key: 'dialog_map', label: '对话-地图', icon: '🗺️', desc: 'Map目录，含replay/precreate/dialog', category: '0.16.0改版' },
    { key: 'dialog_note', label: '对话-纸条', icon: '📝', desc: 'Note目录，含replay/precreate/dialog', category: '0.16.0改版' },
    { key: 'dialog_store', label: '对话-商店', icon: '🏪', desc: 'Store目录，顶层编号条目', category: '0.16.0改版' },
    { key: 'dialog_plot', label: '对话-剧情', icon: '🎬', desc: 'Plot目录，顶层编号条目', category: '0.16.0改版' },
    { key: 'dialog_crusher', label: '对话-谣言烛', icon: '🕯️', desc: 'Crusher目录，含precreate/dialog', category: '0.16.0改版' },
    { key: 'dialog_flat', label: '对话-通用(平铺)', icon: '💬', desc: '顶层编号条目(自动检测)', category: '0.16.0改版' },
    { key: 'crusher_precreate', label: '谣言烛-预创建', icon: '🃏', desc: 'Precreate.json，卡牌/蜡烛/标题', category: '0.16.0改版' },
    { key: 'crusher_detail', label: '谣言烛-详情', icon: '🔍', desc: 'Detail.json，研究/出示数据', category: '0.16.0改版' },
    { key: 'achievement', label: '成就', icon: '🏆', desc: 'Achievement目录，含buttons', category: '0.16.0改版' },
    { key: 'txt_generic', label: '文本文件', icon: '📄', desc: 'TXT标签格式文本', category: '通用' },
    { key: 'recycle_dialog_level', label: '对话-关卡', icon: '📖', desc: 'Levels目录，Day结构含start/编号条目', category: 'Recycle改版' },
    { key: 'recycle_dialog_map', label: '对话-地图', icon: '🗺️', desc: 'Maps目录，Day结构含start/编号条目', category: 'Recycle改版' },
    { key: 'recycle_dialog_crusher', label: '对话-谣言烛', icon: '🕯️', desc: 'Crusher目录，Day结构含start/编号条目', category: 'Recycle改版' },
    { key: 'recycle_dialog_minigame', label: '对话-小游戏', icon: '🎮', desc: 'Minigame目录，Day结构含start/编号条目', category: 'Recycle改版' },
    { key: 'recycle_dialog_note', label: '对话-纸条', icon: '📝', desc: 'Notes目录，含start/编号条目', category: 'Recycle改版' },
    { key: 'recycle_dialog_plot', label: '对话-剧情', icon: '🎬', desc: 'Plots目录，含start/编号条目', category: 'Recycle改版' },
    { key: 'recycle_dialog_store', label: '对话-商店', icon: '🏪', desc: 'Store目录，含start/编号条目', category: 'Recycle改版' }
];

var CHARACTER_OPTIONS = [
    { value: -3, label: '旁白(剧情)' },
    { value: -2, label: '旁白' },
    { value: -1, label: '玩家/史蒂夫' },
    { value: 0, label: '发明家/坑爹村民' },
    { value: 1, label: '欧兰特' },
    { value: 2, label: '哆来咪' },
    { value: 3, label: '朱鹭子' },
    { value: 4, label: '堀川雷鼓' },
    { value: 5, label: '若鹭姬' },
    { value: 6, label: '赤蛮奇' },
    { value: 7, label: '关人正邪' },
    { value: 8, label: '鬼人正邪' },
    { value: 9, label: '今泉影狼' },
    { value: 10, label: '寅丸星' },
    { value: 11, label: '纳兹琳' },
    { value: 12, label: '神子' },
    { value: 13, label: '布都' },
    { value: 14, label: '屠自古' },
    { value: 15, label: '霍青娥' },
    { value: 16, label: '魔理沙' },
    { value: 17, label: '阿求' },
    { value: 18, label: '宫古芳香' },
    { value: 19, label: '二岩猯藏' },
    { value: 20, label: '圣白莲' },
    { value: 21, label: '村纱水蜜' },
    { value: 22, label: '云居一轮' },
    { value: 23, label: '封兽鵺' },
    { value: 24, label: '神龙' },
    { value: 25, label: '福魔/玩家' },
    { value: 26, label: '反转者' },
    { value: 27, label: '幻影' },
    { value: 28, label: '霍青娥(无凿)' },
    { value: 29, label: '角色29' }
];

var CHARACTER_NAME_MAP = {
    '-3': '旁白(剧情)',
    '-2': '旁白',
    '-1': '史蒂夫',
    '0': '发明家',
    '1': '欧兰特',
    '2': '哆来咪',
    '3': '朱鹭子',
    '4': '堀川雷鼓',
    '5': '若鹭姬',
    '6': '赤蛮奇',
    '7': '关人正邪',
    '8': '鬼人正邪',
    '9': '今泉影狼',
    '10': '寅丸星',
    '11': '纳兹琳',
    '12': '神子',
    '13': '布都',
    '14': '屠自古',
    '15': '霍青娥',
    '16': '魔理沙',
    '17': '阿求',
    '18': '宫古芳香',
    '19': '二岩猯藏',
    '20': '圣白莲',
    '21': '村纱水蜜',
    '22': '云居一轮',
    '23': '封兽鵺',
    '24': '神龙',
    '25': '福魔',
    '26': '反转者',
    '27': '幻影',
    '28': '霍青娥(无凿)',
    '29': '角色29'
};

var ACTION_TYPES = [
    { key: 'dialog_type', label: '📋 对话类型', category: 'dialog' },
    { key: 'show_bubble', label: '👁️ 显示对话框', category: 'dialog' },
    { key: 'talking', label: '🗣️ 说话控制', category: 'dialog' },
    { key: 'character_over', label: '🏁 结束对话', category: 'dialog' },
    { key: 'choose', label: '❓ 选择分支', category: 'dialog' },
    { key: 'character_create', label: '🎭 创建角色', category: 'character' },
    { key: 'character_leave', label: '👋 角色离开', category: 'character' },
    { key: 'character_destroy', label: '💀 角色销毁', category: 'character' },
    { key: 'character_change_image', label: '🔄 更换立绘', category: 'character' },
    { key: 'awake', label: '☀️ 角色苏醒', category: 'character' },
    { key: 'set_volume', label: '🔊 音量控制', category: 'audio' },
    { key: 'music_play', label: '🎵 播放BGM', category: 'audio' },
    { key: 'music_stop', label: '⏹ 停止BGM', category: 'audio' },
    { key: 'bubble_image', label: '💬 对话框样式', category: 'visual' },
    { key: 'fading', label: '🌅 场景淡入淡出', category: 'visual' },
    { key: 'color_screen', label: '🎨 屏幕颜色特效', category: 'visual' },
    { key: 'camera_move', label: '📷 镜头移动', category: 'visual' },
    { key: 'wave', label: '👾 设置波次', category: 'gameplay' },
    { key: 'next_wave_timer', label: '⏱ 下一波计时', category: 'gameplay' },
    { key: 'instance_create_depth', label: '🎯 创建实例', category: 'gameplay' },
    { key: 'summon_zombie', label: '🧟 召唤敌人', category: 'gameplay' },
    { key: 'order', label: '🔢 指令序号', category: 'gameplay' },
    { key: 'level_main', label: '⚙️ 关卡控制', category: 'gameplay' },
    { key: 'operate_have', label: '🤚 操作手牌', category: 'gameplay' },
    { key: 'room_goto', label: '🚪 跳转房间', category: 'scene' },
    { key: 'paper_type', label: '📜 纸条类型', category: 'scene' },
    { key: 'plot', label: '📖 剧情进度', category: 'scene' },
    { key: 'plot_room', label: '🏠 剧情房间', category: 'scene' },
    { key: 'wakasagihime_action_play', label: '⚔️ 若鹭姬动作', category: 'special' }
];

var ACTION_DEFAULTS = {
    dialog_type: 0,
    show_bubble: 0,
    talking: 0,
    character_over: 0,
    choose: { types: 2, character: [-1, -1], text: ['选项1', '选项2'], order: [1, 1], title: '请选择' },
    character_create: { character: [0], sprite_index: [1], position: [-1] },
    character_leave: [0],
    character_destroy: [0],
    character_change_image: { character: 0, index: 1 },
    awake: 1,
    set_volume: { to: 0, speed: 0 },
    music_play: '',
    music_stop: 1,
    bubble_image: 1,
    fading: 1,
    color_screen: { color: 1, speed: 1, alpha: 1, time: 1 },
    camera_move: [0, 0],
    wave: 1,
    next_wave_timer: 0,
    instance_create_depth: [900, 392, 0, 94],
    summon_zombie: [15, 3, 1, 1],
    order: 0,
    level_main: { ready_set_weapon: 0 },
    operate_have: 1,
    room_goto: '',
    paper_type: 0,
    plot: 0,
    plot_room: { chapter_over: 0 },
    wakasagihime_action_play: 6
};

var POSITION_OPTIONS = [
    { value: -1, label: '左侧' },
    { value: 0, label: '中间' },
    { value: 1, label: '右侧' }
];

var DEFAULT_DIALOGUE_DATA = {
    "Day1": {
        "001": {
            "character": 0,
            "sound_index": "sndShort2",
            "text": "嘿！我们终于到辉针城了！"
        }
    }
};

var EFFECT_DEFAULTS = [0, 0, 15, 0];

var DIALOG_TYPE_OPTIONS = [
    { value: 0, label: '0 - 普通对话' },
    { value: 1, label: '1 - 选卡对话' },
    { value: 2, label: '2 - 小Boss对话' },
    { value: 3, label: '3 - 大Boss对话' },
    { value: 4, label: '4 - 购买对话' }
];

var CHARACTER_OVER_OPTIONS = [
    { value: 0, label: '0 - 关卡对话结束(入场)' },
    { value: 1, label: '1 - 关卡对话结束' },
    { value: 2, label: '2 - 选卡对话结束' },
    { value: -1, label: '-1 - 小Boss对话结束' }
];

var RECYCLE_CHARACTER_OPTIONS = [
    { value: -3, label: '旁白(回忆)' },
    { value: -2, label: '旁白' },
    { value: -1, label: '史蒂夫/玩家' },
    { value: 0, label: '戴夫/坑爹村民' },
    { value: 1, label: '欧兰特' },
    { value: 2, label: '哆来咪' },
    { value: 3, label: '朱鹭子' },
    { value: 4, label: '堀川雷鼓' },
    { value: 5, label: '若鹭姬' },
    { value: 6, label: '赤蛮奇' },
    { value: 7, label: '关人正邪' },
    { value: 8, label: '鬼人正邪' },
    { value: 9, label: '今泉影狼' },
    { value: 10, label: '寅丸星' },
    { value: 11, label: '纳兹琳' },
    { value: 12, label: '神子' },
    { value: 13, label: '布都' },
    { value: 14, label: '屠自古' },
    { value: 15, label: '霍青娥' },
    { value: 16, label: '魔理沙' },
    { value: 17, label: '阿求' },
    { value: 18, label: '宫古芳香' },
    { value: 19, label: '二岩猯藏' },
    { value: 20, label: '圣白莲' },
    { value: 21, label: '村纱水蜜' },
    { value: 22, label: '云居一轮' },
    { value: 23, label: '封兽鵺' },
    { value: 24, label: '神龙' },
    { value: 25, label: '福魔/玩家' },
    { value: 26, label: '反转者' },
    { value: 27, label: '幻影' },
    { value: 28, label: '霍青娥(无凿)' },
    { value: 29, label: '角色29' }
];

var RECYCLE_CHARACTER_NAME_MAP = {
    '-3': '旁白(回忆)',
    '-2': '旁白',
    '-1': '史蒂夫',
    '0': '戴夫',
    '1': '欧兰特',
    '2': '哆来咪',
    '3': '朱鹭子',
    '4': '堀川雷鼓',
    '5': '若鹭姬',
    '6': '赤蛮奇',
    '7': '关人正邪',
    '8': '鬼人正邪',
    '9': '今泉影狼',
    '10': '寅丸星',
    '11': '纳兹琳',
    '12': '神子',
    '13': '布都',
    '14': '屠自古',
    '15': '霍青娥',
    '16': '魔理沙',
    '17': '阿求',
    '18': '宫古芳香',
    '19': '二岩猯藏',
    '20': '圣白莲',
    '21': '村纱水蜜',
    '22': '云居一轮',
    '23': '封兽鵺',
    '24': '神龙',
    '25': '福魔',
    '26': '反转者',
    '27': '幻影',
    '28': '霍青娥(无凿)',
    '29': '角色29'
};

var RECYCLE_ACTION_TYPES = [
    { key: 'character_over', label: '🏁 结束对话', category: 'dialog' },
    { key: 'choose', label: '❓ 选择分支', category: 'dialog' },
    { key: 'character_create', label: '🎭 创建角色', category: 'character' },
    { key: 'character_leave', label: '👋 角色离开', category: 'character' },
    { key: 'character_show', label: '👁️ 显示角色', category: 'character' },
    { key: 'character_falldown', label: '💀 角色倒下', category: 'character' },
    { key: 'character_change_image', label: '🔄 更换立绘', category: 'character' },
    { key: 'character_wait', label: '⏳ 角色等待', category: 'character' },
    { key: 'character_background_on', label: '🖼️ 显示背景', category: 'visual' },
    { key: 'character_background_off', label: '🖼️ 隐藏背景', category: 'visual' },
    { key: 'ColorScreen', label: '🎨 屏幕颜色', category: 'visual' },
    { key: 'set_volume', label: '🔊 音量控制', category: 'audio' },
    { key: 'music_play', label: '🎵 播放BGM', category: 'audio' },
    { key: 'music_stop', label: '⏹ 停止BGM', category: 'audio' },
    { key: 'show_message', label: '💬 显示消息', category: 'special' },
    { key: 'order_turn_to', label: '↩️ 跳转条目', category: 'special' },
    { key: 'recycle', label: '🔄 重置', category: 'special' }
];

var RECYCLE_ACTION_DEFAULTS = {
    character_over: 0,
    choose: { types: 2, sayingOne: [-1, -1], txt_0: ['选项1', '选项2'], order: [1, 1] },
    character_create: { character: [0], index: [1], pos: [-1] },
    character_leave: [0],
    character_show: { spr: '' },
    character_falldown: [0],
    character_change_image: { character: 0, index: 1 },
    character_wait: { timer: 30, order: 0, offsetSayingOne: 0 },
    character_background_on: { spr: '' },
    character_background_off: 1,
    ColorScreen: { speed: 0.033, alpha: 1, time: 999999 },
    set_volume: { to: 0, speed: 0 },
    music_play: '',
    music_stop: 1,
    show_message: '',
    order_turn_to: 0,
    recycle: 0
};

var TYPE_CATEGORIES = ['0.16.0改版', '通用', 'Recycle改版'];
